### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by darshanrampatel** [xdavidhu/bugs.xdavidhu.me#2]
Great writeups!

Could you please add an RSS feed for your site?

There is a [guide here](https://dzhavat.github.io/2020/01/19/adding-an-rss-feed-to-github-pages.html).

**Comment by xdavidhu** [comment]
Hi,

Thank you for the suggestion, it should be up and running now.
I can see the blog in Feedly, not sure if it picked it up is so quickly, or it was already there, but either way it should work now!

Here is the feed:
https://bugs.xdavidhu.me/feed.xml

Thank you,
David

**Comment by darshanrampatel** [comment]
Thanks! That's working for me.
